### PR TITLE
Make empty commits

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by normanr** [comment]
Also you can override the author and commit details with whatever datetime values you want so this is a bit academic :-P

**Comment by Anant016** [comment]
Yeah, this would make it faster, ok.

**Comment by Anant016** [comment]
I'll merge if this error wasn't coming- "This branch has conflicts that must be resolved."

**Comment by Androbin** [comment]
@Anant016 I rebased the commit. Try again.

**Comment by Anant016** [comment]
Thank you for your contribution, this has increased the performance and time response.

**Pull request merged**
